#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app.swagger:
    path: /api/apidoc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }